# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u8CQHWjurZWmaW8xsooXMlZEYDibSUnh
"""

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/datasets/Gapminder.csv", error_bad_lines=False,sep=";")

df.head()

df = df.rename(columns={"country":"Pais", "continent":"Continente", "year":"Ano", "lifeExp":"Expectativa de vida", "pop":"Pop Total", "gdpPercap":"PIB"})

df.head()

df.head(10)

df.shape

